import { createFileRoute } from "@tanstack/react-router";
import { Check, Eye, EyeOff, Film, LayoutDashboard, Link2, LogOut, Menu, Plus, Save, Settings, ShieldCheck, Trash2, UserRound, X } from "lucide-react";
import { useEffect, useState, type FormEvent, type ReactNode } from "react";
import { supabase } from "../integrations/supabase/client";
import type { Tables } from "../integrations/supabase/types";

export const Route = createFileRoute("/admin")({ head: () => ({ meta: [{ title: "Faith Ekuase CMS | Admin" }] }), component: AdminPage });
type Tab = "overview" | "profile" | "vlogs" | "links" | "settings";
type Vlog = Tables<"vlogs">;
type SocialLink = Tables<"social_links">;
type Content = Tables<"site_content">;

type Field = { key: string; label: string; multiline?: boolean };
const profileFields: Field[] = [{ key: "display_name", label: "Public display name" }, { key: "hero_headline", label: "Hero headline" }, { key: "hero_description", label: "Hero description", multiline: true }, { key: "about_title", label: "About title" }, { key: "about_description", label: "About description", multiline: true }, { key: "course_of_study", label: "Course of study" }, { key: "creator_category", label: "Creator category" }, { key: "short_bio", label: "Short biography", multiline: true }, { key: "location", label: "Location" }, { key: "tagline", label: "Creator tagline" }];
const settingFields: Field[] = [{ key: "browser_title", label: "Browser title" }, { key: "meta_description", label: "Meta description", multiline: true }, { key: "footer_description", label: "Footer description", multiline: true }, { key: "copyright_year", label: "Copyright year" }];

function AdminPage() {
  const [session, setSession] = useState<any>(null); const [ready, setReady] = useState(false); const [mode, setMode] = useState<"login" | "signup">("login"); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [showPassword, setShowPassword] = useState(false); const [authError, setAuthError] = useState(""); const [notice, setNotice] = useState(""); const [tab, setTab] = useState<Tab>("overview"); const [mobile, setMobile] = useState(false); const [vlogs, setVlogs] = useState<Vlog[]>([]); const [links, setLinks] = useState<SocialLink[]>([]); const [profile, setProfile] = useState<Content | null>(null); const [settings, setSettings] = useState<Content | null>(null); const [editing, setEditing] = useState<string | null>(null); const [draft, setDraft] = useState<Partial<Vlog>>({}); const [saving, setSaving] = useState(false);
  const load = async () => { const { data: auth } = await supabase.auth.getSession(); setSession(auth.session); setReady(true); if (!auth.session) return; await supabase.rpc("claim_first_admin", { _user_id: auth.session.user.id }); const [v, l, p, s] = await Promise.all([supabase.from("vlogs").select("*").is("deleted_at", null).order("sort_order"), supabase.from("social_links").select("*").order("sort_order"), supabase.from("site_content").select("*").eq("content_key", "profile").maybeSingle(), supabase.from("site_content").select("*").eq("content_key", "settings").maybeSingle()]); if (v.data) setVlogs(v.data); if (l.data) setLinks(l.data); if (p.data) setProfile(p.data); if (s.data) setSettings(s.data); if (v.error || l.error || p.error || s.error) setNotice("Some workspace content could not be loaded. Refresh and try again."); };
  useEffect(() => { void load(); const { data } = supabase.auth.onAuthStateChange(() => void load()); return () => data.subscription.unsubscribe(); }, []);
  const authenticate = async (event: FormEvent) => { event.preventDefault(); setAuthError(""); const normalized = email.trim().toLowerCase(); if (password.length < 8) { setAuthError("Use a password with at least 8 characters."); return; } const result = mode === "login" ? await supabase.auth.signInWithPassword({ email: normalized, password }) : await supabase.auth.signUp({ email: normalized, password }); if (result.error) { const message = result.error.message.toLowerCase(); setAuthError(message.includes("invalid") ? "Incorrect email or password." : result.error.message); return; } if (!result.data.session) { const retry = await supabase.auth.signInWithPassword({ email: normalized, password }); if (retry.error) { setNotice("Account created. Sign in again to continue."); setMode("login"); return; } } await load(); };
  const addVlog = async () => { setSaving(true); const { data, error } = await supabase.from("vlogs").insert({ title: `Video ${vlogs.length + 1}`, category: "Vlog", description: "", is_visible: false, is_featured: false, media_url: "", thumbnail_url: "", sort_order: vlogs.length + 1 }).select().single(); setSaving(false); if (error) { setNotice(`Could not add vlog: ${error.message}`); return; } if (data) { setVlogs([...vlogs, data]); setEditing(data.id); setDraft(data); setTab("vlogs"); } };
  const saveVlog = async () => { if (!editing) return; setSaving(true); const { error } = await supabase.from("vlogs").update({ ...draft, updated_at: new Date().toISOString() }).eq("id", editing); setSaving(false); if (error) { setNotice(`Could not save vlog: ${error.message}`); return; } setNotice("Vlog saved."); setEditing(null); await load(); };
  const saveContent = async (record: Content | null, fields: Field[], values: Record<string, string>) => { if (!record) { setNotice("This content section is not configured yet."); return; } const merged = { ...(record.content as Record<string, unknown>), ...values }; const { error } = await supabase.from("site_content").update({ content: merged, updated_at: new Date().toISOString() }).eq("content_key", record.content_key); setNotice(error ? `Could not save changes: ${error.message}` : "Changes saved."); if (!error) await load(); void fields; };
  if (!ready) return <div className="admin-loading">Loading workspace</div>;
  if (!session) return <Auth mode={mode} setMode={setMode} email={email} setEmail={setEmail} password={password} setPassword={setPassword} showPassword={showPassword} setShowPassword={setShowPassword} error={authError} notice={notice} authenticate={authenticate} />;
  const nav: [Tab, string, ReactNode][] = [["overview", "Overview", <LayoutDashboard size={16} />], ["profile", "Profile", <UserRound size={16} />], ["vlogs", "Vlogs & videos", <Film size={16} />], ["links", "Links", <Link2 size={16} />], ["settings", "Settings", <Settings size={16} />]];
  return <div className="cms-app"><aside className={mobile ? "cms-sidebar open" : "cms-sidebar"}><div className="cms-brand"><span>FE</span><div><strong>Faith Ekuase</strong><small>Content studio</small></div><button onClick={() => setMobile(false)}><X size={18} /></button></div><nav>{nav.map(([key, label, icon]) => <button key={key} className={tab === key ? "active" : ""} onClick={() => { setTab(key); setMobile(false); }}>{icon}{label}</button>)}</nav><div className="sidebar-bottom"><a href="/" target="_blank">View live site ↗</a><button onClick={async () => { await supabase.auth.signOut(); setSession(null); }}><LogOut size={15} />Log out</button></div></aside><main className="cms-main"><header className="cms-topbar"><button className="mobile-nav-toggle" onClick={() => setMobile(true)}><Menu size={20} /></button><div><p className="eyebrow">Faith Ekuase / CMS</p><h1>{nav.find(([key]) => key === tab)?.[1]}</h1></div><span className="topbar-status"><span className="live-dot" />All changes live</span></header><div className="cms-content">{notice && <div className="cms-notice"><Check size={15} />{notice}<button onClick={() => setNotice("")}><X size={14} /></button></div>}{tab === "overview" && <Overview vlogs={vlogs} links={links} add={addVlog} go={setTab} />}{tab === "vlogs" && <Vlogs vlogs={vlogs} editing={editing} draft={draft} setEditing={setEditing} setDraft={setDraft} add={addVlog} save={saveVlog} saving={saving} />}{tab === "links" && <Links links={links} load={load} notice={setNotice} />}{tab === "profile" && <ContentForm title="Profile & identity" record={profile} fields={profileFields} save={saveContent} />}{tab === "settings" && <ContentForm title="Website settings" record={settings} fields={settingFields} save={saveContent} />}</div></main></div>;
}

function Auth({ mode, setMode, email, setEmail, password, setPassword, showPassword, setShowPassword, error, notice, authenticate }: any) { return <main className="auth-screen"><div className="auth-panel"><div className="admin-mark"><ShieldCheck size={18} /> FE / CMS</div><p className="eyebrow">Private workspace</p><h1>{mode === "login" ? "Welcome back." : "Create your workspace."}</h1><p className="auth-sub">Manage Faith’s website, media, links, and collaborations from one calm place.</p><form className="admin-form" onSubmit={authenticate}><label>Email address<input type="email" value={email} onChange={(e) => setEmail(e.target.value)} required /></label><label>Password<div className="password-field"><input type={showPassword ? "text" : "password"} value={password} onChange={(e) => setPassword(e.target.value)} minLength={8} required /><button type="button" onClick={() => setShowPassword(!showPassword)} aria-label="Toggle password">{showPassword ? <EyeOff size={17} /> : <Eye size={17} />}</button></div></label>{error && <p className="admin-error">{error}</p>}{notice && <p className="admin-success">{notice}</p>}<button className="admin-submit" type="submit">{mode === "login" ? "Sign in" : "Create account"}<span>↗</span></button></form><button className="auth-switch" onClick={() => setMode(mode === "login" ? "signup" : "login")}>{mode === "login" ? "Need an account? Create one" : "Already have an account? Sign in"}</button></div></main>; }
function Overview({ vlogs, links, add, go }: { vlogs: Vlog[]; links: SocialLink[]; add: () => void; go: (tab: Tab) => void }) { return <><div className="welcome-row"><div><p className="eyebrow">Good to see you</p><h2>Your creative home, in one place.</h2><p>Every saved update is connected to the public portfolio.</p></div><button className="admin-submit compact" onClick={add}><Plus size={17} /> Add vlog</button></div><div className="metric-grid"><Metric label="Published vlogs" value={vlogs.filter((v) => v.is_visible && v.media_url).length} icon={<Film />} /><Metric label="Active links" value={links.filter((l) => l.is_visible).length} icon={<Link2 />} /><Metric label="Website status" value="Live" icon={<Check />} /></div><div className="dashboard-grid"><section className="cms-card"><p className="eyebrow">Your library</p><h3>Vlogs & videos</h3>{vlogs.slice(0, 4).map((v) => <div className="mini-row" key={v.id}><strong>{v.title}</strong><small>{v.is_visible ? "Published" : "Draft"}</small></div>)}</section><section className="cms-card quick-card"><p className="eyebrow">Quick actions</p><h3>Make an update</h3><button onClick={() => go("profile")}><UserRound /><span>Edit profile</span></button><button onClick={() => go("links")}><Link2 /><span>Add a social link</span></button></section></div></>; }
function Metric({ label, value, icon }: { label: string; value: string | number; icon: ReactNode }) { return <div className="metric-card"><span className="metric-icon">{icon}</span><strong>{value}</strong><small>{label}</small></div>; }
function Vlogs({ vlogs, editing, draft, setEditing, setDraft, add, save, saving }: any) { return <section><div className="section-intro split"><div><p className="eyebrow">Selected work</p><h2>Vlogs & videos</h2></div><button className="admin-submit compact" onClick={add} disabled={saving}><Plus size={17} /> Add vlog</button></div>{vlogs.map((v: Vlog) => <article className="vlog-item" key={v.id}><div><p className="eyebrow">{v.category}</p><h3>{v.title}</h3><p>{v.description || "No description yet"}</p></div><button onClick={() => { setEditing(v.id); setDraft(v); }}>Edit</button></article>)}{editing && <div className="modal-backdrop"><div className="edit-modal"><button onClick={() => setEditing(null)}><X /></button><h2>Edit vlog</h2><label>Title<input value={draft.title ?? ""} onChange={(e) => setDraft({ ...draft, title: e.target.value })} /></label><label>Category<input value={draft.category ?? ""} onChange={(e) => setDraft({ ...draft, category: e.target.value })} /></label><label>Description<textarea value={draft.description ?? ""} onChange={(e) => setDraft({ ...draft, description: e.target.value })} /></label><button className="admin-submit" onClick={save} disabled={saving}><Save size={16} /> Save vlog</button></div></div>}</section>; }
function Links({ links, load, notice }: { links: SocialLink[]; load: () => Promise<void>; notice: (message: string) => void }) { const [draft, setDraft] = useState({ label: "", url: "", description: "", icon: "link" }); const add = async () => { const { error } = await supabase.from("social_links").insert({ ...draft, sort_order: links.length + 1, is_visible: true }); if (error) notice(`Could not add link: ${error.message}`); else { notice("Link added and published."); setDraft({ label: "", url: "", description: "", icon: "link" }); await load(); } }; return <section><div className="section-intro"><p className="eyebrow">Elsewhere online</p><h2>Social links</h2></div><div className="cms-card edit-card"><label>Platform name<input value={draft.label} onChange={(e) => setDraft({ ...draft, label: e.target.value })} /></label><label>URL<input value={draft.url} onChange={(e) => setDraft({ ...draft, url: e.target.value })} /></label><label>Description<textarea value={draft.description} onChange={(e) => setDraft({ ...draft, description: e.target.value })} /></label><button className="admin-submit" onClick={add}><Plus size={16} /> Add link</button></div><div className="cms-card">{links.map((link) => <div className="link-row" key={link.id}><div><strong>{link.label}</strong><small>{link.url}</small></div><button onClick={async () => { const { error } = await supabase.from("social_links").update({ is_visible: !link.is_visible }).eq("id", link.id); notice(error ? `Could not update link: ${error.message}` : "Link updated."); await load(); }}>{link.is_visible ? "Visible" : "Hidden"}</button><button className="danger" onClick={async () => { await supabase.from("social_links").delete().eq("id", link.id); await load(); }}><Trash2 size={15} /></button></div>)}</div></section>; }
function ContentForm({ title, record, fields, save }: { title: string; record: Content | null; fields: Field[]; save: (record: Content | null, fields: Field[], values: Record<string, string>) => Promise<void> }) { const initial = (record?.content && typeof record.content === "object" && !Array.isArray(record.content) ? record.content : {}) as Record<string, string>; const [values, setValues] = useState(initial); useEffect(() => setValues(initial), [record]); return <section className="form-section"><div className="section-intro"><p className="eyebrow">Content controls</p><h2>{title}</h2></div><div className="cms-card edit-card">{fields.map((field) => <label key={field.key}>{field.label}{field.multiline ? <textarea rows={4} value={values[field.key] ?? ""} onChange={(e) => setValues({ ...values, [field.key]: e.target.value })} /> : <input value={values[field.key] ?? ""} onChange={(e) => setValues({ ...values, [field.key]: e.target.value })} />}</label>)}<button className="admin-submit" onClick={() => void save(record, fields, values)}><Save size={16} /> Save changes</button></div></section>; }
